#####
# dockerfile-kasm-ubuntu-jammy-devops
#
# This is a Dockerfile for building a Kasm Ubuntu Jammy DevOps image.
#####


ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Use Docker root mode
ENV DOCKER_CHANNEL=stable \
	DOCKER_VERSION=20.10.12 \
	DOCKER_COMPOSE_VERSION=1.29.2 \
	DEBUG=false

COPY ./src/ubuntu/install/dind $INST_SCRIPTS/dind/
COPY ./src/ubuntu/install/dind/daemon.json /etc/docker/daemon.json

RUN bash $INST_SCRIPTS/dind/install_dind.sh  && rm -rf $INST_SCRIPTS/dind/



COPY ./src/ubuntu/install/dind/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

COPY ./src/ubuntu/install/dind/modprobe /usr/local/bin/modprobe
RUN chmod +x /usr/local/bin/modprobe
COPY ./src/ubuntu/install/dind/dockerd.conf /etc/supervisor/conf.d/






### Install Tools
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
RUN chmod +x $INST_SCRIPTS/tools/install_tools_deluxe.sh
RUN bash $INST_SCRIPTS/tools/install_tools_deluxe.sh  && rm -rf $INST_SCRIPTS/tools/

# Install Utilities
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/

# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

############### Install Dev Tools ###############

RUN add-apt-repository universe
RUN apt update
RUN apt -y upgrade


### Install Visual Studio Code
COPY ./src/ubuntu/install/vs_code $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_vs_code.sh  && rm -rf $INST_SCRIPTS/vs_code/

### Install NodeJS


### Terminal and Fonts

# Install Starship
RUN wget https://starship.rs/install.sh
RUN chmod +x install.sh
RUN ./install.sh -y

# Add Starship to bashrc
RUN echo 'eval "$(starship init bash)"' >> .bashrc

# Add Starship Theme
COPY ./src/assets/config/starship.toml .config/starship.toml

# Install Hack Nerd Font
RUN wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.1/Hack.zip
RUN unzip Hack.zip -d /usr/local/share/fonts

RUN apt update
# Install Terminator
RUN apt -y install terminator
 

# Set up Nerd font in Terminator
RUN mkdir .config/terminator
COPY ./src/assets/config/terminator.toml .config/terminator/config

# Install XFCE Dark Theme
RUN apt -y install numix-gtk-theme


### Backgroud
# RUN wget https://cdn.hipwallpaper.com/i/92/9/0Ts6mr.png -O /usr/share/extra/backgrounds/bg_default.png
COPY ./src/assets/backgrounds/wallpaper-code.jpg /usr/share/extra/backgrounds/bg_default.png

# Copy version file
COPY ./src/daboss/devops-version.txt /home 



######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
